10min Group Assignment - Answers
=================
Choose one of the following challenges.

1. Create a paneled ggplot figure using facet_wrap() that shows the allometric relationship between mass and wingchord for each clade. Add a **linear** smoothing line following the instructions in stat_smooth()

```{r}
traits<-read.csv("C:/Users/Ben/Desktop/Traits.csv")
require(ggplot2)
#Create new column for the w/m ratio
traits$w_m<-traits$WingChord/traits$Mass

ggplot(traits,aes(x=Mass,y=WingChord,col=Clade)) + geom_point() + geom_smooth(method="lm",aes(group=1)) + facet_wrap(~Clade)
ggplot(traits,aes(x=Species,y=w_m)) + geom_point() + geom_smooth(aes(group=1),method="lm") + facet_wrap(~Clade,scales="free")                                                                                         
```

2. Does the number of species in a genus relate to the variance in body size?

```{r}
#Find the number of species in a genus using a cotingency table
sp_g<-data.frame(table(traits$Genus))

#name the columns
colnames(sp_g)<-c("Genus","N")

for (i in 1:nrow(sp_g)){
genus<-sp_g[i,"Genus"]
#subset the data for that genus
genus_t<-traits[traits$Genus == genus,]
#Get the variance in bill size and place it in an output
sp_g[i,"Var_bill"]<-var(genus_t$Bill)
}

#plot the result
ggplot(sp_g,aes(x=N,y=Var_bill)) + geom_point() + geom_smooth()
ggplot(sp_g,aes(x=N,y=Var_bill)) + geom_point() + geom_smooth(method="lm") + ylim(0,12)
```
